DROP database h2o;
CREATE Database h2o;

USE h2o;

CREATE TABLE H2OUSER (
 USER_ID BIGINT NOT NULL,
 DELETED CHAR(1) NOT NULL DEFAULT 'N',
 LOGONID VARCHAR(254),
 LOGONPASSWORD VARCHAR(64),
 FIRSTNAME VARCHAR(128),
 LASTNAME VARCHAR(128),
 PHONE VARCHAR(32),
 EMAIL VARCHAR(256)
);

ALTER TABLE H2OUSER
  ADD CONSTRAINT PK_H2OUSER
  PRIMARY KEY (USER_ID);

CREATE TABLE THINGS (
 THINGS_ID BIGINT NOT NULL,
 DELETED CHAR(1) NOT NULL DEFAULT 'N',
 NAME VARCHAR(254)
);

ALTER TABLE THINGS
  ADD CONSTRAINT PK_THINGS
  PRIMARY KEY (THINGS_ID);

CREATE TABLE USER_THINGS (
 USER_ID BIGINT NOT NULL,
 THINGS_ID BIGINT NOT NULL
);

ALTER TABLE USER_THINGS
ADD CONSTRAINT FK_USER
FOREIGN KEY (USER_ID)
REFERENCES H2OUSER(USER_ID) ON DELETE CASCADE;

ALTER TABLE USER_THINGS
ADD CONSTRAINT FK_THINGS
FOREIGN KEY (THINGS_ID)
REFERENCES THINGS(THINGS_ID) ON DELETE CASCADE;

CREATE TABLE UNITS (
 UNITS_ID INTEGER NOT NULL,
 NAME VARCHAR(254)
);

CREATE TABLE THINGS_DATA (
 DATA_ID BIGINT NOT NULL,
 THINGS_ID BIGINT NOT NULL,
 UNITS_ID INTEGER NOT NULL,
 LOGGEDIN_TIME  TIMESTAMP NOT NULL,
 DATA DECIMAL(20,5) NOT NULL DEFAULT 0
);

ALTER TABLE THINGS_DATA
  ADD CONSTRAINT PK_THINGS_DATA
  PRIMARY KEY (DATA_ID);

ALTER TABLE THINGS_DATA
ADD CONSTRAINT FK_THINGS_DATA
FOREIGN KEY (THINGS_ID)
REFERENCES THINGS(THINGS_ID) ON DELETE CASCADE;

ALTER TABLE THINGS_DATA MODIFY DATA_ID BIGINT AUTO_INCREMENT;
ALTER TABLE THINGS_DATA MODIFY LOGGEDIN_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;